import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { HomeContextProvider } from "@/context/HomeContext";
import { ModalContextProvider } from "@/context/ModalContext";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kanban",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <HomeContextProvider>
          <ModalContextProvider>{children}</ModalContextProvider>
        </HomeContextProvider>
      </body>
    </html>
  );
}
